# 📊 Customer Churn Analysis

## Business Understanding

Customer churn is one of the major challenges in subscription-based industries.  
This project aims to analyze customer behavior patterns and identify factors contributing to churn risk.

STEP 1.1 — IMPORT LIBRARY

In [9]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from plotly.subplots import make_subplots

STEP 1.2 — LOAD DATA

In [5]:
df = pd.read_csv("../data/churn.csv")

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

STEP 1.3 — BASIC INFO

In [18]:
print(df.shape)

df.info()

df.describe()

(7032, 21)
<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7032.000000  7032.000000     7032.000000   7032.000000
mean        0.162400    32.421786       64.798208   2283.300441
std         0.368844    24.545260       30.085974   2266.771362
min         0.000000     1.000000       18.250000     18.800000
25%         0.000000     9.000000       35.587500    401.450000
50%         0.000000    29.000000       70.350000   1397.475000
75%         0.000000    55.000000       89.862500   3794.737500
max         1.000000    72.000000      118.750000   8684.800000

In [10]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 7032
Columns : 21

STEP 1.4 — CHECK MISSING VALUE

In [19]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

STEP 1.5 — DATA CLEANING

In [20]:
df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)

df["TotalCharges"].fillna(df["TotalCharges"].median(), inplace=True)

STEP 1.6 — CHURN DISTRIBUTION

In [21]:
fig = px.pie(
    df,
    names='Churn',
    title='Customer Churn Distribution',
    hole=0.6,
    color='Churn',
    color_discrete_map={
        'Yes': '#F59E0B',
        'No': '#22C55E'
    }
)

fig.update_layout(
    paper_bgcolor='#0F172A',
    plot_bgcolor='#0F172A',
    font_color='white',
    title_font_size=24
)

fig.show()

INSIGHT

The dataset shows a noticeable imbalance between churned and retained customers, indicating that customer retention remains a critical business challenge.

STEP 1.7 — TENURE ANALYSIS

In [22]:
fig = px.histogram(
    df,
    x='tenure',
    color='Churn',
    nbins=30,
    title='Customer Tenure Distribution by Churn Status',
    color_discrete_map={
        'Yes': '#F59E0B',
        'No': '#6366F1'
    }
)

fig.update_layout(
    paper_bgcolor='#0F172A',
    plot_bgcolor='#0F172A',
    font_color='white'
)

fig.show()

INSIGHT

Customers with shorter subscription tenure exhibit a significantly higher churn tendency compared to long-term customers.

STEP 1.8 — CONTRACT TYPE ANALYSIS

In [23]:
contract_churn = pd.crosstab(
    df['Contract'],
    df['Churn'],
    normalize='index'
)

contract_churn = contract_churn.reset_index()

fig = px.bar(
    contract_churn,
    x='Contract',
    y='Yes',
    title='Churn Rate by Contract Type',
    color='Yes',
    color_continuous_scale='Oranges'
)

fig.update_layout(
    paper_bgcolor='#0F172A',
    plot_bgcolor='#0F172A',
    font_color='white'
)

fig.show()

INSIGHT

Month-to-month contracts demonstrate substantially higher churn rates, suggesting weaker long-term customer commitment.

STEP 1.9 — MONTHLY CHARGES ANALYSIS

In [24]:
fig = px.box(
    df,
    x='Churn',
    y='MonthlyCharges',
    color='Churn',
    title='Monthly Charges Distribution by Churn',
    color_discrete_map={
        'Yes': '#F59E0B',
        'No': '#22C55E'
    }
)

fig.update_layout(
    paper_bgcolor='#0F172A',
    plot_bgcolor='#0F172A',
    font_color='white'
)

fig.show()

INSIGHT

Customers with higher monthly charges tend to exhibit greater churn probability, potentially indicating pricing sensitivity.

STEP 1.10 — CORRELATION HEATMAP

In [25]:
numeric_df = df.select_dtypes(include=['int64', 'float64'])

corr = numeric_df.corr()

fig = px.imshow(
    corr,
    text_auto=True,
    color_continuous_scale='Blues',
    title='Correlation Heatmap'
)

fig.update_layout(
    paper_bgcolor='#0F172A',
    plot_bgcolor='#0F172A',
    font_color='white'
)

fig.show()

STEP 2 — Feature Engineering + Preprocessing

STEP 2.1 — IMPORT LIBRARY

In [26]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

STEP 2.2 — LOAD DATA

In [27]:
df = pd.read_csv("../data/churn.csv")

STEP 2.3 — CLEANING TOTALCHARGES

In [28]:
df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)

df["TotalCharges"].fillna(
    df["TotalCharges"].median(),
    inplace=True
)

STEP 2.4 — DROP UNUSED COLUMN

In [29]:
df.drop("customerID", axis=1, inplace=True)

STEP 2.5 — FEATURE ENGINEERING

In [30]:
df["TenureGroup"] = pd.cut(
    df["tenure"],
    bins=[0,12,24,48,72],
    labels=[
        "0-12 Months",
        "12-24 Months",
        "24-48 Months",
        "48-72 Months"
    ]
)

STEP 2.6 — ENCODE TARGET

In [31]:
df["Churn"] = df["Churn"].map({
    "Yes": 1,
    "No": 0
})

STEP 2.7 — ENCODE CATEGORICAL FEATURES

In [32]:
df = pd.get_dummies(
    df,
    drop_first=True
)

STEP 2.8 — SPLIT FEATURE & TARGET

In [33]:
X = df.drop("Churn", axis=1)

y = df["Churn"]

STEP 2.9 — TRAIN TEST SPLIT

In [34]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

STEP 2.10 — FEATURE SCALING

In [35]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

STEP 2.11 — CHECK SHAPE

In [36]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (5634, 33)
X_test : (1409, 33)
y_train: (5634,)
y_test : (1409,)

In [37]:
print(y_train.value_counts(normalize=True))

print(y_test.value_counts(normalize=True))

Churn
0    0.734647
1    0.265353
Name: proportion, dtype: float64
Churn
0    0.734564
1    0.265436
Name: proportion, dtype: float64

INSIGHT

The preprocessing stage transforms raw customer data into a structured machine learning-ready dataset through feature engineering, encoding, and scaling techniques.

STEP 3.1 — IMPORT LIBRARY

In [38]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    roc_curve
)

c:\Users\wildan nabila\AppData\Local\Programs\Python\Python310\lib\site-packages\xgboost\compat.py:105: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

STEP 3.2 — LOAD PREPROCESSED DATA

STEP 3.3 — LOGISTIC REGRESSION

In [39]:
log_model = LogisticRegression(max_iter=1000)

log_model.fit(X_train_scaled, y_train)

log_pred = log_model.predict(X_test_scaled)

log_prob = log_model.predict_proba(X_test_scaled)[:,1]

STEP 3.4 — EVALUATION FUNCTION

In [40]:
def evaluate_model(y_true, y_pred, y_prob, model_name):

    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)
    roc_auc = roc_auc_score(y_true, y_prob)

    print(f"===== {model_name} =====")
    print("Accuracy :", round(accuracy,4))
    print("Precision:", round(precision,4))
    print("Recall   :", round(recall,4))
    print("F1 Score :", round(f1,4))
    print("ROC AUC  :", round(roc_auc,4))

    return {
        "Model": model_name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1,
        "ROC AUC": roc_auc
    }

STEP 3.5 — EVALUATE LOGISTIC

In [41]:
log_result = evaluate_model(
    y_test,
    log_pred,
    log_prob,
    "Logistic Regression"
)

===== Logistic Regression =====
Accuracy : 0.7991
Precision: 0.6522
Recall   : 0.5214
F1 Score : 0.5795
ROC AUC  : 0.842

STEP 3.6 — RANDOM FOREST

In [42]:
rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

rf_prob = rf_model.predict_proba(X_test)[:,1]

STEP 3.7 — EVALUATE RF

In [43]:
rf_result = evaluate_model(
    y_test,
    rf_pred,
    rf_prob,
    "Random Forest"
)

===== Random Forest =====
Accuracy : 0.7885
Precision: 0.6293
Recall   : 0.4947
F1 Score : 0.5539
ROC AUC  : 0.824

STEP 3.8 — XGBOOST

In [44]:
xgb_model = XGBClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=4,
    random_state=42,
    eval_metric='logloss'
)

xgb_model.fit(X_train, y_train)

xgb_pred = xgb_model.predict(X_test)

xgb_prob = xgb_model.predict_proba(X_test)[:,1]

STEP 3.9 — EVALUATE XGB

In [45]:
xgb_result = evaluate_model(
    y_test,
    xgb_pred,
    xgb_prob,
    "XGBoost"
)

===== XGBoost =====
Accuracy : 0.8041
Precision: 0.6644
Recall   : 0.5294
F1 Score : 0.5893
ROC AUC  : 0.8425

STEP 3.10 — MODEL COMPARISON TABLE

In [46]:
results = pd.DataFrame([
    log_result,
    rf_result,
    xgb_result
])

results

                 Model  Accuracy  Precision    Recall  F1 Score   ROC AUC
0  Logistic Regression  0.799148   0.652174  0.521390  0.579495  0.842050
1        Random Forest  0.788502   0.629252  0.494652  0.553892  0.824015
2              XGBoost  0.804116   0.664430  0.529412  0.589286  0.842499

STEP 3.11 — VISUAL COMPARISON

In [47]:
fig = px.bar(
    results.melt(id_vars="Model"),
    x="variable",
    y="value",
    color="Model",
    barmode="group",
    title="Model Performance Comparison"
)

fig.update_layout(
    paper_bgcolor='#0F172A',
    plot_bgcolor='#0F172A',
    font_color='white',
    title_font_size=24
)

fig.show()

STEP 3.12 — CONFUSION MATRIX

In [48]:
cm = confusion_matrix(y_test, xgb_pred)

fig = px.imshow(
    cm,
    text_auto=True,
    color_continuous_scale='Blues',
    title='Confusion Matrix - XGBoost'
)

fig.update_layout(
    paper_bgcolor='#0F172A',
    plot_bgcolor='#0F172A',
    font_color='white'
)

fig.show()

STEP 3.13 — ROC CURVE

In [49]:
fpr_log, tpr_log, _ = roc_curve(y_test, log_prob)
fpr_rf, tpr_rf, _ = roc_curve(y_test, rf_prob)
fpr_xgb, tpr_xgb, _ = roc_curve(y_test, xgb_prob)

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=fpr_log,
    y=tpr_log,
    mode='lines',
    name='Logistic Regression'
))

fig.add_trace(go.Scatter(
    x=fpr_rf,
    y=tpr_rf,
    mode='lines',
    name='Random Forest'
))

fig.add_trace(go.Scatter(
    x=fpr_xgb,
    y=tpr_xgb,
    mode='lines',
    name='XGBoost'
))

fig.update_layout(
    title='ROC Curve Comparison',
    xaxis_title='False Positive Rate',
    yaxis_title='True Positive Rate',
    paper_bgcolor='#0F172A',
    plot_bgcolor='#0F172A',
    font_color='white'
)

fig.show()

STEP 3.14 — FEATURE IMPORTANCE

In [50]:
importance = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': xgb_model.feature_importances_
})

importance = importance.sort_values(
    by='Importance',
    ascending=False
).head(10)

fig = px.bar(
    importance,
    x='Importance',
    y='Feature',
    orientation='h',
    title='Top 10 Important Features'
)

fig.update_layout(
    paper_bgcolor='#0F172A',
    plot_bgcolor='#0F172A',
    font_color='white'
)

fig.show()

INSIGHT

The modeling stage demonstrates that ensemble-based methods outperform baseline linear models in capturing complex churn behavior patterns.

STEP 4.1 — PREDICTION PROBABILITY

In [51]:
churn_prob = xgb_model.predict_proba(X_test)[:,1]

STEP 4.2 — CREATE PROBABILITY DATAFRAME

In [52]:
result_df = X_test.copy()

result_df["Actual_Churn"] = y_test.values

result_df["Churn_Probability"] = churn_prob

STEP 4.3 — THRESHOLD TUNING

STEP 4.4 — TEST MULTIPLE THRESHOLD

In [53]:
thresholds = [0.3, 0.4, 0.5, 0.6]

for threshold in thresholds:

    pred = (churn_prob >= threshold).astype(int)

    recall = recall_score(y_test, pred)

    precision = precision_score(y_test, pred)

    f1 = f1_score(y_test, pred)

    print(f"Threshold: {threshold}")
    print("Recall   :", round(recall,4))
    print("Precision:", round(precision,4))
    print("F1 Score :", round(f1,4))
    print("-"*40)

Threshold: 0.3
Recall   : 0.762
Precision: 0.5367
F1 Score : 0.6298
----------------------------------------
Threshold: 0.4
Recall   : 0.6444
Precision: 0.5807
F1 Score : 0.6109
----------------------------------------
Threshold: 0.5
Recall   : 0.5294
Precision: 0.6644
F1 Score : 0.5893
----------------------------------------
Threshold: 0.6
Recall   : 0.3717
Precision: 0.7316
F1 Score : 0.4929
----------------------------------------

STEP 4.5 — APPLY BEST THRESHOLD

In [54]:
best_threshold = 0.4

result_df["Predicted_Churn"] = (
    result_df["Churn_Probability"] >= best_threshold
).astype(int)

STEP 4.6 — CREATE RISK SEGMENTATION

In [55]:
def risk_segment(prob):

    if prob >= 0.75:
        return "🔴 High Risk"

    elif prob >= 0.40:
        return "🟠 Medium Risk"

    else:
        return "🟢 Low Risk"

result_df["Risk_Level"] = result_df[
    "Churn_Probability"
].apply(risk_segment)

STEP 4.7 — VISUAL RISK DISTRIBUTION

In [56]:
risk_counts = result_df["Risk_Level"].value_counts()

fig = px.pie(
    values=risk_counts.values,
    names=risk_counts.index,
    title="Customer Churn Risk Distribution",
    hole=0.6,
    color=risk_counts.index,
    color_discrete_map={
        "🔴 High Risk": "#EF4444",
        "🟠 Medium Risk": "#F59E0B",
        "🟢 Low Risk": "#22C55E"
    }
)

fig.update_layout(
    paper_bgcolor='#0F172A',
    plot_bgcolor='#0F172A',
    font_color='white'
)

fig.show()

STEP 4.8 — TOP HIGH RISK CUSTOMERS

In [57]:
high_risk = result_df[
    result_df["Risk_Level"] == "🔴 High Risk"
]

high_risk[
    ["Churn_Probability", "Risk_Level"]
].head(10)

      Churn_Probability   Risk_Level
2280           0.838360  🔴 High Risk
346            0.750026  🔴 High Risk
6633           0.868554  🔴 High Risk
2519           0.825894  🔴 High Risk
880            0.760471  🔴 High Risk
2246           0.854499  🔴 High Risk
5300           0.825805  🔴 High Risk
642            0.807248  🔴 High Risk
1334           0.793550  🔴 High Risk
2448           0.757712  🔴 High Risk

STEP 4.9 — BUSINESS ACTION TABLE

In [58]:
strategy = pd.DataFrame({

    "Risk Level": [
        "🔴 High Risk",
        "🟠 Medium Risk",
        "🟢 Low Risk"
    ],

    "Recommended Action": [
        "Immediate retention campaign & discount offer",
        "Personalized engagement campaign",
        "Maintain loyalty program"
    ]
})

strategy

      Risk Level                             Recommended Action
0    🔴 High Risk  Immediate retention campaign & discount offer
1  🟠 Medium Risk               Personalized engagement campaign
2     🟢 Low Risk                       Maintain loyalty program

STEP 4.10 — BUSINESS INSIGHT VISUAL

In [59]:
avg_prob = result_df.groupby(
    "Risk_Level"
)["Churn_Probability"].mean().reset_index()

fig = px.bar(
    avg_prob,
    x="Risk_Level",
    y="Churn_Probability",
    color="Risk_Level",
    title="Average Churn Probability by Risk Level",
    color_discrete_map={
        "🔴 High Risk": "#EF4444",
        "🟠 Medium Risk": "#F59E0B",
        "🟢 Low Risk": "#22C55E"
    }
)

fig.update_layout(
    paper_bgcolor='#0F172A',
    plot_bgcolor='#0F172A',
    font_color='white'
)

fig.show()

INSIGHT

Threshold tuning enables the business to balance customer retention effectiveness and campaign efficiency by adjusting sensitivity toward potential churners.

BUSINESS RECOMMENDATION

Customers categorized as high-risk should be prioritized for proactive retention strategies such as personalized offers, loyalty incentives, and customer engagement programs.

STEP 5 — EXECUTIVE DASHBOARD